package edu.byu.cs.superasteroids.main_menu;

import android.util.Log;

import edu.byu.cs.superasteroids.base.IView;
import edu.byu.cs.superasteroids.content.ContentManager;
import edu.byu.cs.superasteroids.model_classes.Asteroid;
import edu.byu.cs.superasteroids.model_classes.AsteroidsGame;
import edu.byu.cs.superasteroids.model_classes.Ship;

/**
 * Created by athom909 on 2/26/16.
 * this has all been autogenerated up to this point
 */
public class MainMenuController implements IMainMenuController {

    private MainActivity mainActivity;

    public MainMenuController(MainActivity mainActivity) {
        this.mainActivity = mainActivity;
    }

    /**
     * implements the "Quick Play" feature
     * automatically builds a complete ship in the model, and starts the game by calling startGame()
     *  on its view
     */
    @Override
    public void onQuickPlayPressed() {
        AsteroidsGame.getInstance().loadShipParts(ContentManager.getInstance());
        AsteroidsGame.getInstance().setShip();
        mainActivity.startGame();
    }

    @Override
    public IView getView() {
        return null;
    }

    @Override
    public void setView(IView view) {

    }
}
